- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/chrome.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/time.yml
    - include_tasks: tasks/andrew.yml
