---
  - name: Download the wallpaper image
    become_user: andrew
    get_url:
      url: "https://cdn.eso.org/images/screen/eso0932a.jpg"
      dest: "/home/andrew/Pictures/wallpaper.jpg"
      owner: andrew
      group: andrew
      mode: '0644'

  - name: Set GNOME wallpaper
    become_user: andrew
    community.general.dconf:
      key: /org/gnome/desktop/background/picture-uri
      value: "'file:///home/andrew/Pictures/wallpaper.jpg'"
      state: present

  - name: Set 24 Hour Clock
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/clock-format" value="'24h'"

  - name: Set Clock Show Weekday
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/clock-show-weekday" value="'true'"

  - name: Set Top Bar Show Battery Percentage
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/show-battery-percentage" value="'true'"

  - name: Set dock position to bottom for all users
    ansible.builtin.shell: 
      gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
    args:
      executable: /bin/bash # Ensure bash is used for shell module
    become_user: andrew # Replace 'your_user' or ensure ansible_user is defined
      # This task needs to be run as the user whose GNOME settings you want to change.
      # If you're managing multiple users, you might need a loop or to run this for each user.
      # For a single user, `ansible_user` often works, but explicitly setting it is safer.
      # If you want to apply it globally for new users, that's a more complex GDM/skeleton setup.
      # This playbook targets existing user's settings.

  - name: Display success message
    ansible.builtin.debug:
      msg: "Ubuntu Dock has been moved to the bottom of the screen."

  - name: Disable "extend to screen edge" for the dock (to center it)
        ansible.builtin.shell: 
          gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
        args:
          executable: /bin/bash
        become_user: andrew
