---
  - name: Download the wallpaper image
    become_user: andrew
    get_url:
      url: "https://cdn.eso.org/images/screen/eso0932a.jpg"
      dest: "/home/andrew/Pictures/wallpaper.jpg"
      owner: andrew
      group: andrew
      mode: '0644'

  - name: Set GNOME wallpaper
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///home/andrew/Pictures/wallpaper.jpg'"
      state: present
  
  - name: Set 24 Hour Clock
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/desktop/interface/clock-format" 
      value: "'24h'"
      state: present
    

  - name: Set Clock Show Weekday
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/desktop/interface/clock-show-weekday" 
      value: "'true'"
      state: present

  - name: Set Top Bar Show Battery Percentage
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/desktop/interface/show-battery-percentage" 
      value: "'true'"
      state: present

  - name: Set dock position to bottom using dconf
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/dock-position" 
      value: "'BOTTOM'"
      state: present

  - name: Disable "extend to screen edge" (to center it) using dconf
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/extend-height" 
      value: "false"
      state: present

  - name: Disable natural scrolling for touchpad (enables traditional scrolling)
    become_user: andrew
    community.general.dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll" 
      value: "false"
      state: present
