- name: install cron job (ansible-pull-client-system)
  cron:
    user: svc_ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/arunstedler/AnsiblePullClientSystem-Minimal.git > /var/log/ansible-pull-log.txt"

- name: install cron job (stop caffeine @ 10pm)
  cron:
    user: andrew
    name: "stop caffeine"
    day: "*"
    hour: "22"
    job: "caffeine -x"
