- name: Install packages
  apt:
    name:
      - htop
      - tmux
      - caffeine
      - vlc
      - gnome-shell-extension-prefs
      - gnome-shell-extension-manager
      - gedit-plugins
      - gnome-tweaks
      - gnome-sushi
      - gnome-session
      - chrome-gnome-shell
      - freeipa-client
      - ubuntu-restricted-extras
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - gnome-software-plugin-flatpak
      - wireshark
      - clamav
      - clamav-daemon
  when: ansible_distribution == "Ubuntu"
  
- name: Install packages
  apt:
    name:
      - htop
      - tmux
      - caffeine
      - vlc
      - gnome-shell-extension-prefs
      - gnome-shell-extension-manager
      - gedit-plugins
      - gnome-tweaks
      - gnome-sushi
      - gnome-session
      - chrome-gnome-shell
      - freeipa-client
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - gnome-software-plugin-flatpak
      - wireshark
      - clamav
      - clamav-daemon
  when: ansible_os_family == "Debian"

  
- name: Install packages
  dnf:
    name:
      - htop
      - tmux
      - vlc
      - gedit-plugins
      - gnome-extensions-app
      - gnome-shell-extension-dash-to-dock
      - gnome-tweaks
      - gnome-session
      - freeipa-client
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - wireshark
      - clamav
  when: ansible_os_family == "RedHat"

- name: Install packages
  snap:
    name:
      - bitwarden
      - discord
  when: ansible_os_family == "Debian"

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: termix
    state: present
    method: user
    flatpakrepo_url: https://github.com/Termix-SSH/Termix/releases/latest/download/termix_linux_flatpak.flatpak
  when: ansible_os_family == "Debian"

- name: Install a Flatpak application 
  community.general.flatpak:
    name: com.karmaa.termix
    state: present
    method: user
    remote: termix
  when: ansible_os_family == "Debian"
