- name: Install packages (Ubuntu)
  apt:
    name:
      - htop
      - tmux
      - caffeine
      - vlc
      - gnome-shell-extension-prefs
      - gnome-shell-extension-manager
      - gedit-plugins
      - gnome-tweaks
      - gnome-sushi
      - gnome-session
      - chrome-gnome-shell
      - freeipa-client
      - ubuntu-restricted-extras
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - gnome-software-plugin-flatpak
      - wireshark
      - clamav
      - clamav-daemon
  when: ansible_distribution == "Ubuntu"
  
- name: Install packages (Debian)
  apt:
    name:
      - htop
      - tmux
      - caffeine
      - vlc
      - gnome-shell-extension-prefs
      - gnome-shell-extension-manager
      - gedit-plugins
      - gnome-tweaks
      - gnome-sushi
      - gnome-session
      - chrome-gnome-shell
      - freeipa-client
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - gnome-software-plugin-flatpak
      - wireshark
      - clamav
      - clamav-daemon
  when: ansible_distribution == "Debian"

- name: Install packages (Kali)
  apt:
    name:
      - htop
      - tmux
      - caffeine
      - vlc
      - gnome-shell-extension-prefs
      - gnome-shell-extension-manager
      - gedit-plugins
      - gnome-tweaks
      - gnome-sushi
      - gnome-session
      - chrome-gnome-shell
      - freeipa-client
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - gnome-software-plugin-flatpak
      - wireshark
      - clamav
      - clamav-daemon
  when: ansible_distribution == "Kali GNU/Linux"

  
- name: Install packages (Fedora)
  dnf:
    name:
      - htop
      - tmux
      - vlc
      - gedit-plugins
      - gnome-extensions-app
      - gnome-shell-extension-dash-to-dock
      - gnome-tweaks
      - gnome-session
      - freeipa-client
      - sssd-tools
      - syncthing
      - gh
      - python3-pip
      - python3-psutil
      - solaar
      - flatpak
      - wireshark
      - clamav
  when: ansible_distribution == "Fedora"

- name: Install packages
  snap:
    name:
      - bitwarden
      - discord
  when: ansible_distribution == "Ubuntu"
